ingress:
  enabled: true
  path: '/'
service:
  enabled: true
  name: front
  externalPort: 3000
  internalPort: 3000
livenessProbe:
  enabled: false
  path: '/status'
readinessProbe:
  enabled: false
  path: '/status'
application:
  track: stable
  tier: backend
  part: backend
  migrateCommand: []
image:
  pullPolicy: Always
